version: '3.1'

services:

  db:
    image: postgres:15.1
    restart: always
    hostname: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
  ide:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    # Enables terminal mode
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 8080:8978
    volumes:
      - ./workspace/:/opt/cloudbeaver/workspace
    depends_on:
      - db